name: simple_e-commerceapi
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Retrieve the MongoDB URI
        run: echo "MONGO_URI=${{ secrets.MONGO_URI }}" > .env
      - run: npm ci
      - run: npm start
