name: simple_e-commerceapi

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
      

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
    - uses: actions/checkout@v4.2.2
     with:
        node-version: 20
    - run : npm help
    - run : npm ci
    - run : npm run build

